### ISSUE TITLE
Add Seconds to the option

### ISSUE THREAD

**Issue by Dimi15** [Zwyx/vscode-autoclosetabs#1]
### Please add the possibility to give the value of seconds to the `"autoclosetabs.tabAgeForAutomaticClosing"` option.

I'd really like to get my non-active tabs closed periodically, so that I end up having open the only one that I'm currently in. Thanks!

**Comment by Zwyx** [comment]
Thanks for the suggestion, I'll try to work on it!

Meanwhile, [this extension](https://marketplace.visualstudio.com/items?itemName=martinmeinke.autoclose) works differently and does allow you to set an age in seconds. Maybe it would fit your needs better for the moment?

**Comment by Zwyx** [comment]
Let's close this issue as this isn't a feature that would be easy to implement, and alternatives exist.
